### ISSUE TITLE
#parse function will never return 

### ISSUE THREAD

**Issue by eeeyes** [kschiess/parslet#143]
when you call parse function like this 'Parslet::str('a').maybe.repeat(1).parse('a')' , then the parse function will never return.

**Comment by dancinglightning** [comment]
@eeeyes I think the syntax wobbled a bit (no rule, no input), but maybe i know what you mean:
Peg parsers don't do left recursion. You can try an read up about it.
Usually (i think in theory always) there there is a way to transform the grammar so that left recursion doesn't happen.
You should probably close the issue (as it is not parslets fault) , though i don't mind if you ask more questions. There is a mailing list for this kind of thing, but admittedly it's clumsy.

**Comment by kschiess** [comment]
This says: 

* Match 'a'
* zero or more times
* repeat the above at least once

an endless loop. Parslet's behaviour is correct.
