### ISSUE TITLE
Is it possible to access tree output when parse fails?

### ISSUE THREAD

**Issue by rupy** [kschiess/parslet#196]
Hi, I'd like to know if I can access tree output built by "as" at that moment when parse fails.
if so, debug becomes much easier.

Any help will be appreciated.

**Comment by kschiess** [comment]
Tree output can only be constructed once a parse succeeds. Otherwise the output is underdetermined, there would be many trees to consider. Have a look at 

https://github.com/kschiess/parslet/blob/master/example/deepest_errors.rb

for how to use alternative error reporters. Also - the implementation of that error reporter could be interesting to you; maybe you want to contribute another one?
